# Generated by Django 5.1 on 2024-09-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='document_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='exam_period',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registernumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=2415, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
