# Generated by Django 5.1 on 2024-09-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_document_type_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='document_type',
        ),
    ]
