# Generated by Django 5.1 on 2024-09-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_password_student_regno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='regno',
            new_name='roll_number',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
